// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '../../types/database.types';

const SUPABASE_URL = "https://xxeapzrjjdnnikxmuvqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh4ZWFwenJqamRubmlreG11dnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTgwNzgsImV4cCI6MjA1ODg5NDA3OH0.s8GH3gTg2Pu0sexVHA2JOlnOqJTl-fCaU0jR6VZZIZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);